services:
  db:
    image: postgres:17-alpine
    container_name: employee-db
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      - employee_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - app-network
  app:
    container_name: employee-checkin
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=target/*.jar
    image: employee-checking-platform:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_OPEN_IN_VIEW=true
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC
      - WAIT_FOR_DB=db:5432
    restart: unless-stopped
    networks:
      - app-network
volumes:
  employee_pgdata:

networks:
  app-network:
    driver: bridge