server:
  port: ${SERVER_PORT:8080}
  ssl:
    certificate: classpath:certs/cert.pem
    certificate-private-key: classpath:certs/privkey.pem

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Employee Checking Platform}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_checking}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}

  jpa:
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update} # prod’da flyway/liqibase tavsiya etiladi
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${HIBERNATE_DEFAULT_BATCH_FETCH_SIZE:50}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    root: ${LOG_ROOT_LEVEL:INFO}
    org.springframework.web: ${LOG_WEB_LEVEL:INFO}
    org.hibernate.SQL: ${LOG_HIBERNATE_SQL_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_HIBERNATE_BIND_LEVEL:WARN}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-operation-id: true
    try-it-out-enabled: true
    persist-authorization: true

app:
  jwt:
    # Hech qachon kodga secretni qattiq yozmang; .env dan oling
    secret: ${APP_JWT_SECRET:change_this_to_a_256bit_random_secret_at_least_32_chars_long}
    access-exp-min: ${APP_JWT_ACCESS_EXP_MIN:60}  # 60 daqiqa
  admin:
    username: ${APP_ADMIN_USERNAME:admin}   # .env orqali bering; bo'sh bo'lsa seed SKIP
    password: ${APP_ADMIN_PASSWORD:admin}
    name: ${APP_ADMIN_NAME:Super Admin}
  tashkilot:
    name: ${APP_TASHKILOT_NAME:Mudofaa vazirligi}
    turi: ${APP_TASHKILOT_TURI:MV}

  face:
    token:
      url: ${FACE_TOKEN_URL:http://192.168.202.17:8002/api/v1/auth/oauth2/token}
      basic-username: ${FACE_BASIC_USERNAME:test-user-1}
      basic-password: ${FACE_BASIC_PASSWORD:G9xLm4RtP2qVz8Wk}
      username: ${FACE_RO_USERNAME:test-user-1}
      password: ${FACE_RO_PASSWORD:X7dK9pQa}
    upload:
      url: ${FACE_UPLOAD_URL:http://192.168.202.17:8002/api/v1/faceid/recognize}
      param-name: ${FACE_UPLOAD_PARAM:image}
      as-form: ${FACE_UPLOAD_AS_FORM:true}
      data-uri: ${FACE_UPLOAD_DATA_URI:false}
      include-filename: ${FACE_UPLOAD_INCLUDE_FILENAME:true}
      include-content-type: ${FACE_UPLOAD_INCLUDE_CONTENT_TYPE:true}
      default-is-photo: ${FACE_UPLOAD_DEFAULT_IS_PHOTO:Y}

application:
  title: |
    Bu platforma _______varizligi hodimlarining
    bilim va ko'nikmalarini baholash uchun yaratildi
  version: |
    version 1.0.0

external:
  basic:
    username: external-server
    password: BASIC_PASS_123
  jwt:
    username: api-client
    password: JWT_PASS_456

jwt:
  secret: "MY_JWT_SECRET_KEY_123"
  expiration-ms: 3600000

